name: Upload File to Release

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: "URL to download the file from"
        required: true
        type: string
      release_tag:
        description: "Release tag for the upload"
        required: true
        type: string

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download File with Tag Name as Filename
        run: |
          curl -L ${{ github.event.inputs.download_url }} -o "${{ github.event.inputs.release_tag }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: Release ${{ github.event.inputs.release_tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.inputs.release_tag }}
          asset_name: ${{ github.event.inputs.release_tag }}
          asset_content_type: application/octet-stream
