name: Upload File to Release

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: "URL to download the file from"
        required: true
        type: string

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Filename from URL
        id: extract_filename
        run: |
          filename=$(basename "${{ github.event.inputs.download_url }}")
          tag_name="${filename%.*}"  # Remove file extension to create tag name
          echo "filename=$filename" >> $GITHUB_ENV
          echo "tag_name=$tag_name" >> $GITHUB_ENV

      - name: Download File
        run: |
          curl -L ${{ github.event.inputs.download_url }} -o "${{ env.filename }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ env.tag_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.filename }}
          asset_name: ${{ env.filename }}
          asset_content_type: application/octet-stream
